### ISSUE TITLE
HDF5ExtError: Problems creating the Array.

### ISSUE THREAD

**Issue by francoislaurent** [DecBayComp/RWA-python#1]
```
Traceback (most recent call last):
  File "job_manager.py", line 51, in <module>
    main(cur_args)
  File "main.py", line 34, in main
    tesselate_and_infer(file)
  File "tesselate_and_infer.py", line 28, in tesselate_and_infer
    verbose=True, force=True)  # , ref_distance = 0.05)
  File "tramway/helper/tessellation.py", line 492, in tessellate
    force=force or (len(input_files)==1 and input_files[0]==output_file))
  File "tramway/core/hdf5/store.py", line 107, in save_rwa
    store.poke('analyses', analyses)
  File "tramway/core/hdf5/store.py", line 56, in poke
    HDF5Store.poke(self, objname, obj, container, visited)
  File "/usr/local/lib/python3.5/dist-packages/rwa/hdf5.py", line 292, in poke
    FileStore.poke(self, objname, obj, container, visited=visited)
  File "/usr/local/lib/python3.5/dist-packages/rwa/lazy.py", line 68, in poke
    GenericStore.poke(self, objname, lazyvalue(obj, deep=True), record, visited)
  File "/usr/local/lib/python3.5/dist-packages/rwa/generic.py", line 144, in poke
    self.pokeStorable(storable, objname, obj, record, visited=visited)
  File "/usr/local/lib/python3.5/dist-packages/rwa/generic.py", line 93, in pokeStorable
    storable.poke(self, objname, obj, container, visited=visited)
  File "/usr/local/lib/python3.5/dist-packages/rwa/generic.py", line 199, in _poke
    store.poke(iobjname, iobj, sub_container, visited=visited)
  File "tramway/core/hdf5/store.py", line 56, in poke
    HDF5Store.poke(self, objname, obj, container, visited)
  File "/usr/local/lib/python3.5/dist-packages/rwa/hdf5.py", line 292, in poke
    FileStore.poke(self, objname, obj, container, visited=visited)
  File "/usr/local/lib/python3.5/dist-packages/rwa/lazy.py", line 68, in poke
    GenericStore.poke(self, objname, lazyvalue(obj, deep=True), record, visited)
  File "/usr/local/lib/python3.5/dist-packages/rwa/generic.py", line 144, in poke
    self.pokeStorable(storable, objname, obj, record, visited=visited)
  File "/usr/local/lib/python3.5/dist-packages/rwa/generic.py", line 93, in pokeStorable
    storable.poke(self, objname, obj, container, visited=visited)
  File "/usr/local/lib/python3.5/dist-packages/rwa/hdf5.py", line 123, in poke_Pandas
    obj.to_hdf(tmpfilename, 'root')
  File "/usr/local/lib/python3.5/dist-packages/pandas/core/generic.py", line 1471, in to_hdf
    return pytables.to_hdf(path_or_buf, key, self, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pandas/io/pytables.py", line 281, in to_hdf
    f(store)
  File "/usr/local/lib/python3.5/dist-packages/pandas/io/pytables.py", line 275, in <lambda>
    f = lambda store: store.put(key, value, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pandas/io/pytables.py", line 866, in put
    self._write_to_group(key, value, append=append, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pandas/io/pytables.py", line 1341, in _write_to_group
    s.write(obj=value, append=append, complib=complib, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/pandas/io/pytables.py", line 2923, in write
    self.write_index('axis%d' % i, ax)
  File "/usr/local/lib/python3.5/dist-packages/pandas/io/pytables.py", line 2513, in write_index
    self.write_array(key, converted.values)
  File "/usr/local/lib/python3.5/dist-packages/pandas/io/pytables.py", line 2723, in write_array
    self._handle.create_array(self.group, key, value)
  File "/usr/local/lib/python3.5/dist-packages/tables/file.py", line 1146, in create_array
    obj=obj, title=title, byteorder=byteorder)
  File "/usr/local/lib/python3.5/dist-packages/tables/array.py", line 187, in __init__
    byteorder, _log)
  File "/usr/local/lib/python3.5/dist-packages/tables/leaf.py", line 272, in __init__
    super(Leaf, self).__init__(parentnode, name, _log)
  File "/usr/local/lib/python3.5/dist-packages/tables/node.py", line 266, in __init__
    self._v_objectid = self._g_create()
  File "/usr/local/lib/python3.5/dist-packages/tables/array.py", line 219, in _g_create
    nparr, self._v_new_title, self.atom)
  File "tables/hdf5extension.pyx", line 1249, in tables.hdf5extension.Array._create_array (tables/hdf5extension.c:15394)
tables.exceptions.HDF5ExtError: Problems creating the Array.
```

**Comment by francoislaurent** [comment]
This particular bug instance might be due to insufficient storage space and may be classified as an error documentation issue.

The bug - if confirmed - should be reported in the `tables` project.

**Comment by francoislaurent** [comment]
Never reproduced.
