### ISSUE TITLE
range() does not take keyword arguments

### ISSUE THREAD

**Issue by francoislaurent** [DecBayComp/RWA-python#2]
``range`` poked with Python 3.6.8, peeked with Python 3.5.2:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/rwa/lazy.py", line 112, in peek
    **self.kwargs)
  File "/usr/local/lib/python3.5/dist-packages/rwa/generic.py", line 407, in peekStorable
    return storable.peek(self, record, _stack=_stack, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/rwa/storable.py", line 108, in peek
    return self._peek(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/rwa/pandas.py", line 265, in peek_dataframe
    df = _peek_dataframe(service, container, _stack=_stack)
  File "/usr/local/lib/python3.5/dist-packages/rwa/generic.py", line 671, in _peek
    for objname in exposes ]
  File "/usr/local/lib/python3.5/dist-packages/rwa/generic.py", line 671, in <listcomp>
    for objname in exposes ]
  File "/usr/local/lib/python3.5/dist-packages/tramway/core/hdf5/store.py", line 68, in peek
    obj = HDF5Store.peek(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/rwa/hdf5.py", line 379, in peek
    return FileStore.peek(self, objname, record, _stack=_stack, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/rwa/lazy.py", line 54, in peek
    return GenericStore.peek(self, objname, container, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/rwa/generic.py", line 424, in peek
    obj = self.peekStorable(storable, record, _stack=_stack, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/rwa/lazy.py", line 66, in peekStorable
    return GenericStore.peekStorable(self, storable, record, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/rwa/generic.py", line 407, in peekStorable
    return storable.peek(self, record, _stack=_stack, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/rwa/storable.py", line 108, in peek
    return self._peek(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/rwa/pandas.py", line 30, in _peek_index
    index = peek(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/rwa/pandas.py", line 171, in peek_rangeindex
    step=attrs.pop('_step', None)), \
TypeError: range() does not take keyword arguments
```

Python 3.6.8 and 3.6.9 can load the same file without any problem.

**Comment by francoislaurent** [comment]
The bug actually affected `pandas.RangeIndex` and not built-in `range`.
